In [10]:
import numpy as np
import os
os.chdir("D:\DATA SCIENCE")
data=np.loadtxt("population.txt")

In [11]:
data

array([[ 1900., 38000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400.,  8300., 42300.],
       [ 1908., 22000.,  9100., 44500.],
       [ 1909., 25400.,  7400., 42100.],
       [ 1910., 27100.,  8000., 46000.],
       [ 1911., 48300., 12300., 46800.],
       [ 1912., 57000., 19500., 43800.],
       [ 1913., 76600., 45700., 40900.],
       [ 1914., 52300., 51100., 39400.],
       [ 1915., 19500., 29700., 36700.],
       [ 1916., 11200., 15800., 41800.],
       [ 1917.,  7600.,  9700., 43300.],
       [ 1918., 14600., 10100., 41300.],
       [ 1919., 16200.,  8600., 43700.],
       [ 1920., 24700.,  7400., 42800.]])

In [12]:
year,hare,lynx,carrot=data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [13]:
# mean population over time
population = data[:,1:]
population

array([[38000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400.,  8300., 42300.],
       [22000.,  9100., 44500.],
       [25400.,  7400., 42100.],
       [27100.,  8000., 46000.],
       [48300., 12300., 46800.],
       [57000., 19500., 43800.],
       [76600., 45700., 40900.],
       [52300., 51100., 39400.],
       [19500., 29700., 36700.],
       [11200., 15800., 41800.],
       [ 7600.,  9700., 43300.],
       [14600., 10100., 41300.],
       [16200.,  8600., 43700.],
       [24700.,  7400., 42800.]])

In [14]:
# sample standard devation
population.std(axis=0)

array([21068.13372141, 16415.12078774,  3071.35843405])

In [16]:
# which species has the highest population each year
np.argmax(population,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2],
      dtype=int64)

  ##  Broadcasting
  
  Basic operation on numpy array(addition,..etc) are elementwise.
  
  Broadcasting work on array of same size. It is also possible to do operation on arrays of different sizes if Numpy can transform these arraya so that they all have the same size this conversion is called broadcasting.

In [20]:
a=np.tile(np.arange(0,40,10),(3,1))       # replicate these 3 times along row
print(a)

a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [19]:
a=np.tile(np.arange(0,40,10),(3,2))       # replicate these 3 times along row and 2 time along column
print(a)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [21]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [22]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [23]:
a=np.arange(0,40,10)
a.shape

(4,)

In [24]:
a=a[:,np.newaxis]           #  add a new axis ---> 2D array
a.shape

(4, 1)

In [25]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [26]:
a.ndim

2

In [27]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

# Array shape manipulation

  ## Flattening

In [33]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()       # return a contiguous flatttened array

array([1, 2, 3, 4, 5, 6])

In [34]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

# Reshapimg

In [37]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [38]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [39]:
b = b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
b[0,0]=100

a

array([[100,   2,   3],
       [  4,   5,   6]])

NOTE:- reshape may also return a copy

In [42]:
a=np.zeros((3,2))
b=a.T.reshape(3*2)
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

 Adding a Dimension

Indexing with the np.newaxis object allows us to add an axis to any array.
Increase a dimension of exixting array by 1.
1 D ---------> 2 D array
2 D ---------> 3 D array

In [43]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [44]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

# Dimension Shuffling

In [49]:
a=np.arange(4*3*2).reshape(4,3,2)      # 4 matrix each of size 3x2
print(a.shape)
a

(4, 3, 2)


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [50]:
a[0,2,1]

5

Resizing

In [54]:
a=np.arange(4)
a.resize((8,))
print(a)
a.resize((8,2))
a

[0 1 2 3 0 0 0 0]


array([[0, 1],
       [2, 3],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [55]:
b=a
b.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

## Sorting Data

In [56]:
# sorting along axis:
a=np.array([[5,4,6],[2,3,2]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [58]:
# in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [59]:
# sorting with fancy indexing
a=np.array([4,3,1,2])
j=np.argsort(a)                # return the index position in sorted order
j

array([2, 3, 1, 0], dtype=int64)

In [60]:
a[j]

array([1, 2, 3, 4])